/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bostonchildcare.View;

import Helpers.FieldValidator;
import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTextField;

/**
 *
 * @author amarn
 */
public class StudentEnrollmentForm_View extends javax.swing.JFrame {

    /**
     * Creates new form StudentEnrollmentForm_View
     */
    private static final StudentEnrollmentForm_View instance = new StudentEnrollmentForm_View();
    private StudentEnrollmentForm_View() {
        initComponents();
    }
    public static StudentEnrollmentForm_View getInstance(){
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfname_label = new javax.swing.JLabel();
        sfname_field = new javax.swing.JTextField();
        slname_label = new javax.swing.JLabel();
        slname_field = new javax.swing.JTextField();
        sage_label = new javax.swing.JLabel();
        pfname_label = new javax.swing.JLabel();
        plname_label = new javax.swing.JLabel();
        contact_label = new javax.swing.JLabel();
        pfname_field = new javax.swing.JTextField();
        plname_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        submit_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        sage_field = new javax.swing.JFormattedTextField();
        contact_field = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sfname_label.setText("Student's FirstName");

        slname_label.setText("Student's LastName");

        slname_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slname_fieldActionPerformed(evt);
            }
        });

        sage_label.setText("Student's Age(months)");

        pfname_label.setText("Parent's FirstName");

        plname_label.setText("Parent's LastName");

        contact_label.setText("Contact E-mail");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel7.setText("New Student Enrollment Form");

        submit_button.setText("Submit");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });

        cancel_button.setText("Cancel");

        try {
            sage_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        contact_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sage_label)
                    .addComponent(pfname_label)
                    .addComponent(plname_label)
                    .addComponent(contact_label)
                    .addComponent(sfname_label)
                    .addComponent(slname_label))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancel_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(submit_button))
                    .addComponent(plname_field)
                    .addComponent(pfname_field)
                    .addComponent(slname_field)
                    .addComponent(sfname_field)
                    .addComponent(sage_field)
                    .addComponent(contact_field))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sfname_label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sfname_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slname_label)
                    .addComponent(slname_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sage_label)
                    .addComponent(sage_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfname_label)
                    .addComponent(pfname_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plname_label)
                    .addComponent(plname_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contact_label)
                    .addComponent(contact_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit_button)
                    .addComponent(cancel_button))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slname_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slname_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slname_fieldActionPerformed

    private void contact_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contact_fieldActionPerformed

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_submit_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StudentEnrollmentForm_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StudentEnrollmentForm_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StudentEnrollmentForm_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StudentEnrollmentForm_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StudentEnrollmentForm_View().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JFormattedTextField contact_field;
    private javax.swing.JLabel contact_label;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField pfname_field;
    private javax.swing.JLabel pfname_label;
    private javax.swing.JTextField plname_field;
    private javax.swing.JLabel plname_label;
    private javax.swing.JFormattedTextField sage_field;
    private javax.swing.JLabel sage_label;
    private javax.swing.JTextField sfname_field;
    private javax.swing.JLabel sfname_label;
    private javax.swing.JTextField slname_field;
    private javax.swing.JLabel slname_label;
    private javax.swing.JButton submit_button;
    // End of variables declaration//GEN-END:variables

    
    public JButton getCancel_button() {
        return cancel_button;
    }

    public void setCancel_button(JButton cancel_button) {
        this.cancel_button = cancel_button;
    }

    public JFormattedTextField getContact_field() {
        return contact_field;
    }

    public void setContact_field(JFormattedTextField contact_field) {
        this.contact_field = contact_field;
    }

    
    public JTextField getPfname_field() {
        return pfname_field;
    }

    public void setPfname_field(JTextField pfname_field) {
        this.pfname_field = pfname_field;
    }

    public JTextField getPlname_field() {
        return plname_field;
    }

    public void setPlname_field(JTextField plname_field) {
        this.plname_field = plname_field;
    }

    public JFormattedTextField getSage_field() {
        return sage_field;
    }

    public void setSage_field(JFormattedTextField sage_field) {
        this.sage_field = sage_field;
    }

   

    public JTextField getSfname_field() {
        return sfname_field;
    }

    public void setSfname_field(JTextField sfname_field) {
        this.sfname_field = sfname_field;
    }

    public JTextField getSlname_field() {
        return slname_field;
    }

    public void setSlname_field(JTextField slname_field) {
        this.slname_field = slname_field;
    }

    public JButton getSubmit_button() {
        return submit_button;
    }

    public void setSubmit_button(JButton submit_button) {
        this.submit_button = submit_button;
    }
}
