/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bostonchildcare.View;

import javax.swing.JButton;

/**
 *
 * @author amarn
 */
public class Student_Teacher_Selection_View extends javax.swing.JFrame {

    /**
     * Creates new form Student_Teacher_Selection_View
     */
    private static final Student_Teacher_Selection_View instance = new Student_Teacher_Selection_View();
    private Student_Teacher_Selection_View() {
        initComponents();
    }
    public static Student_Teacher_Selection_View getinstance(){
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student_pane_button = new javax.swing.JButton();
        teacher_pane_button = new javax.swing.JButton();
        new_student_enrollment_button = new javax.swing.JButton();
        existing_student_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        student_pane_button.setText("Student");
        student_pane_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_pane_buttonActionPerformed(evt);
            }
        });

        teacher_pane_button.setText("Teacher");

        new_student_enrollment_button.setText("New Student Enrollment");
        new_student_enrollment_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_student_enrollment_buttonActionPerformed(evt);
            }
        });

        existing_student_button.setText("Existing Student");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(existing_student_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(new_student_enrollment_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(student_pane_button, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(223, 223, 223))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(teacher_pane_button, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_pane_button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacher_pane_button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(new_student_enrollment_button)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(existing_student_button)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void new_student_enrollment_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_student_enrollment_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_student_enrollment_buttonActionPerformed

    private void student_pane_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_pane_buttonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_student_pane_buttonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Teacher_Selection_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Teacher_Selection_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Teacher_Selection_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Teacher_Selection_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Teacher_Selection_View().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton existing_student_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton new_student_enrollment_button;
    private javax.swing.JButton student_pane_button;
    private javax.swing.JButton teacher_pane_button;
    // End of variables declaration//GEN-END:variables

    public JButton getExisting_student_button() {
        return existing_student_button;
    }

    public void setExisting_student_button(JButton existing_student_button) {
        this.existing_student_button = existing_student_button;
    }

    public JButton getNew_student_enrollment_button() {
        return new_student_enrollment_button;
    }

    public void setNew_student_enrollment_button(JButton new_student_enrollment_button) {
        this.new_student_enrollment_button = new_student_enrollment_button;
    }

    public JButton getStudent_pane_button() {
        return student_pane_button;
    }

    public void setStudent_pane_button(JButton student_pane_button) {
        this.student_pane_button = student_pane_button;
    }

    public JButton getTeacher_pane_button() {
        return teacher_pane_button;
    }

    public void setTeacher_pane_button(JButton teacher_pane_button) {
        this.teacher_pane_button = teacher_pane_button;
    }


    
}
